/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { CacheFirst, NetworkFirst, NetworkOnly } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'

declare let self: ServiceWorkerGlobalScope

// Clean up old caches
cleanupOutdatedCaches()

// Precache all assets generated by vite
precacheAndRoute(self.__WB_MANIFEST)

// Cache map tiles
registerRoute(
  /^https:\/\/.*\.basemaps\.cartocdn\.com\/.*/i,
  new CacheFirst({
    cacheName: 'map-tiles',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 500,
        maxAgeSeconds: 60 * 60 * 24 * 7, // 7 days
      }),
    ],
  })
)

// Real-time aircraft data should always go to network (no caching)
registerRoute(
  /\/api\/aircraft(?:\/search)?$/,
  new NetworkOnly()
)

// SignalR hubs should always use network
registerRoute(
  /\/hubs\//,
  new NetworkOnly()
)

// Weather data can use NetworkFirst with short cache (changes slowly)
registerRoute(
  /\/api\/weather/,
  new NetworkFirst({
    cacheName: 'weather-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 5, // 5 minutes
      }),
    ],
  })
)

// Health endpoints use network only
registerRoute(
  /\/health|\/api\/health/,
  new NetworkOnly()
)

// Handle notification clicks
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  const data = event.notification.data || {}
  const actionUrl = data.actionUrl || '/'

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // Check if app is already open
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.navigate(actionUrl)
          return client.focus()
        }
      }
      // Open new window if not already open
      if (self.clients.openWindow) {
        return self.clients.openWindow(actionUrl)
      }
    })
  )
})

// Handle notification close (for analytics)
self.addEventListener('notificationclose', (event) => {
  const data = event.notification.data || {}
  console.log('Notification closed:', data.alertType)
})

// Handle push events (for future server-sent push notifications)
self.addEventListener('push', (event) => {
  if (!event.data) return

  try {
    const payload = event.data.json()

    const options = {
      body: payload.body || '',
      icon: payload.icon || '/logo.png',
      badge: '/favicon.svg',
      tag: payload.tag || 'aerolens-notification',
      data: payload.data || {},
      vibrate: [200, 100, 200],
      requireInteraction: payload.requireInteraction || false,
    } as NotificationOptions & { vibrate?: number[] }

    event.waitUntil(self.registration.showNotification(payload.title || 'AeroLens', options))
  } catch (error) {
    console.error('Error handling push event:', error)
  }
})
